export const boardData = {
  table: [
    {
      id: 0,
      type: "exit",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 1,
      type: "property",
      name: " CSS",
      versionAlpha: 2,
      versionOne: 10,
      versionTwo: 30,
      versionThree: 90,
      versionFour: 160,
      versionPremium: 250,
      aditional: "además V4.0",
      commonVersion: 50,
      premiumVersion: 50,
      licenseValue: 30,
      color: "brown",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 2,
      type: "comunal",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 3,
      type: "property",
      name: "HTML",
      versionAlpha: 4,
      versionOne: 20,
      versionTwo: 60,
      versionThree: 80,
      versionFour: 320,
      versionPremium: 450,
      aditional: "además V4.0",
      commonVersion: 50,
      premiumVersion: 50,
      licenseValue: 30,
      color: "brown",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 4,
      type: "tax",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 5,
      type: "railway",
      name: "HENRY M1",
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: 25,
      twoCheckpoint: 50,
      threeCheckpoint: 100,
      fourCheckpoint: 200,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 6,
      type: "property",
      name: "Postgres",
      versionAlpha: 6,
      versionOne: 30,
      versionTwo: 90,
      versionThree: 270,
      versionFour: 400,
      versionPremium: 550,
      aditional: "además V4.0",
      commonVersion: 50,
      premiumVersion: 50,
      licenseValue: 50,
      color: "light-blue",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 7,
      type: "lucky",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 8,
      type: "property",
      name: "SQLITE",
      versionAlpha: 6,
      versionOne: 30,
      versionTwo: 90,
      versionThree: 270,
      versionFour: 400,
      versionPremium: 550,
      aditional: "además V4.0",
      commonVersion: 50,
      premiumVersion: 50,
      licenseValue: 50,
      color: "light-blue",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 9,
      type: "property",
      name: "MySQL",
      versionAlpha: 8,
      versionOne: 40,
      versionTwo: 100,
      versionThree: 300,
      versionFour: 450,
      versionPremium: 600,
      aditional: "además V4.0",
      commonVersion: 50,
      premiumVersion: 50,
      licenseValue: 60,
      color: "light-blue",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 10,
      type: "jail",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 11,
      type: "property",
      name: "C#",
      versionAlpha: 10,
      versionOne: 50,
      versionTwo: 150,
      versionThree: 450,
      versionFour: 625,
      versionPremium: 750,
      aditional: "además V4.0",
      commonVersion: 100,
      premiumVersion: 100,
      licenseValue: 70,
      color: "pink",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 12,
      type: "service",
      name: "ELECTRICITY COMPANY",
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: 75,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 13,
      type: "property",
      name: "C++",
      versionAlpha: 10,
      versionOne: 50,
      versionTwo: 150,
      versionThree: 450,
      versionFour: 625,
      versionPremium: 750,
      aditional: "además V4.0",
      commonVersion: 100,
      premiumVersion: 100,
      licenseValue: 70,
      color: "pink",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 14,
      type: "property",
      name: "C",
      versionAlpha: 12,
      versionOne: 60,
      versionTwo: 180,
      versionThree: 500,
      versionFour: 700,
      versionPremium: 900,
      aditional: "además V4.0",
      commonVersion: 100,
      premiumVersion: 100,
      licenseValue: 80,
      color: "pink",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 15,
      type: "railway",
      name: "HENRY M2",
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: 25,
      twoCheckpoint: 50,
      threeCheckpoint: 100,
      fourCheckpoint: 200,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 16,
      type: "property",
      name: "BootStrap",
      versionAlpha: 14,
      versionOne: 70,
      versionTwo: 200,
      versionThree: 550,
      versionFour: 750,
      versionPremium: 950,
      aditional: "además V4.0",
      commonVersion: 100,
      premiumVersion: 100,
      licenseValue: 90,
      color: "orange",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 17,
      type: "comunal",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 18,
      type: "property",
      name: "Diseño UI/UX",
      versionAlpha: 14,
      versionOne: 70,
      versionTwo: 200,
      versionThree: 550,
      versionFour: 750,
      versionPremium: 950,
      aditional: "además V4.0",
      commonVersion: 100,
      premiumVersion: 100,
      licenseValue: 90,
      color: "orange",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 19,
      type: "property",
      name: "Express",
      versionAlpha: 16,
      versionOne: 80,
      versionTwo: 220,
      versionThree: 600,
      versionFour: 800,
      versionPremium: 1000,
      aditional: "además V4.0",
      commonVersion: 100,
      premiumVersion: 100,
      licenseValue: 100,
      color: "orange",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 20,
      type: "stop",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 21,
      type: "property",
      name: "Vue",
      versionAlpha: 18,
      versionOne: 90,
      versionTwo: 250,
      versionThree: 700,
      versionFour: 875,
      versionPremium: 1050,
      aditional: "además V4.0",
      commonVersion: 150,
      premiumVersion: 150,
      licenseValue: 110,
      color: "red",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 22,
      type: "lucky",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 23,
      type: "property",
      name: "Angular",
      versionAlpha: 18,
      versionOne: 90,
      versionTwo: 250,
      versionThree: 700,
      versionFour: 875,
      versionPremium: 1050,
      aditional: "además V4.0",
      commonVersion: 150,
      premiumVersion: 150,
      licenseValue: 110,
      color: "red",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 24,
      type: "property",
      name: "Node",
      versionAlpha: 20,
      versionOne: 100,
      versionTwo: 300,
      versionThree: 750,
      versionFour: 925,
      versionPremium: 1100,
      aditional: "además V4.0",
      commonVersion: 150,
      premiumVersion: 150,
      licenseValue: 120,
      color: "red",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 25,
      type: "railway",
      name: "HENRY M3",
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: 25,
      twoCheckpoint: 50,
      threeCheckpoint: 100,
      fourCheckpoint: 200,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 26,
      type: "property",
      name: "Python",
      versionAlpha: 22,
      versionOne: 110,
      versionTwo: 330,
      versionThree: 800,
      versionFour: 975,
      versionPremium: 1150,
      aditional: "además V4.0",
      commonVersion: 150,
      premiumVersion: 150,
      licenseValue: 130,
      color: "yellow",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 27,
      type: "property",
      name: "Java",
      versionAlpha: 22,
      versionOne: 110,
      versionTwo: 330,
      versionThree: 800,
      versionFour: 975,
      versionPremium: 1150,
      aditional: "además V4.0",
      commonVersion: 150,
      premiumVersion: 150,
      licenseValue: 130,
      color: "yellow",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 28,
      type: "service",
      name: "INTERNET COMPANY",
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: 75,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 29,
      type: "property",
      name: "JavaScript",
      versionAlpha: 22,
      versionOne: 110,
      versionTwo: 330,
      versionThree: 800,
      versionFour: 975,
      versionPremium: 1150,
      aditional: "además V4.0",
      commonVersion: 150,
      premiumVersion: 150,
      licenseValue: 130,
      color: "yellow",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 30,
      type: "goJail",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 31,
      type: "property",
      name: "Sequelize",
      versionAlpha: 26,
      versionOne: 130,
      versionTwo: 390,
      versionThree: 900,
      versionFour: 1100,
      versionPremium: 1275,
      aditional: "además V4.0",
      commonVersion: 200,
      premiumVersion: 200,
      licenseValue: 150,
      color: "green",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 32,
      type: "property",
      name: "GitHub",
      versionAlpha: 26,
      versionOne: 130,
      versionTwo: 390,
      versionThree: 900,
      versionFour: 1100,
      versionPremium: 1275,
      aditional: "además V4.0",
      commonVersion: 200,
      premiumVersion: 200,
      licenseValue: 150,
      color: "green",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 33,
      type: "comunal",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 34,
      type: "property",
      name: "Git",
      versionAlpha: 28,
      versionOne: 150,
      versionTwo: 450,
      versionThree: 1000,
      versionFour: 1200,
      versionPremium: 1400,
      aditional: "además V4.0",
      commonVersion: 200,
      premiumVersion: 200,
      licenseValue: 160,
      color: "green",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 35,
      type: "railway",
      name: "HENRY M4",
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: 25,
      twoCheckpoint: 50,
      threeCheckpoint: 100,
      fourCheckpoint: 200,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 36,
      type: "lucky",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 37,
      type: "property",
      name: "Redux",
      versionAlpha: 35,
      versionOne: 175,
      versionTwo: 500,
      versionThree: 1100,
      versionFour: 1300,
      versionPremium: 1500,
      aditional: "además V4.0",
      commonVersion: 200,
      premiumVersion: 200,
      licenseValue: 175,
      color: "blue",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 38,
      type: "taxVip",
      name: null,
      versionAlpha: null,
      versionOne: null,
      versionTwo: null,
      versionThree: null,
      versionFour: null,
      versionPremium: null,
      aditional: null,
      commonVersion: null,
      premiumVersion: null,
      licenseValue: null,
      color: null,
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    },
    {
      id: 39,
      type: "property",
      name: "React",
      versionAlpha: 50,
      versionOne: 200,
      versionTwo: 600,
      versionThree: 1400,
      versionFour: 1700,
      versionPremium: 2000,
      aditional: "además V4.0",
      commonVersion: 200,
      premiumVersion: 200,
      licenseValue: 200,
      color: "blue",
      takeCheckpoint: null,
      twoCheckpoint: null,
      threeCheckpoint: null,
      fourCheckpoint: null,
      numberBox: null,
      tableMasterID: null
    }
  ],
  fortune: [
    {
      id: 1,
      name: "Suerte",
      description: "No comiteaste bien | Retrocede 3 casilleros",
      tableMasterID: null
    },
    {
      id: 2,
      name: "Suerte",
      description: "No creaste bien tu rama | Retrocede 4 casilleros",
      tableMasterID: null
    },
    {
      id: 3,
      name: "Suerte",
      description: "Te aceptaron de TA | Cobra un bonus de $5",
      tableMasterID: null
    },
    {
      id: 4,
      name: "Suerte",
      description: "Nuevos impuestos en Argentina | Paga $2 por cada versión normal y $6 por cada versión premium que tengas",
      tableMasterID: null
    },
    {
      id: 5,
      name: "Suerte",
      description: "Te cortaron la luz, perdiste 3 dias en el PI | Retrocede 3 espacios",
      tableMasterID: null
    },
    {
      id: 6,
      name: "Suerte",
      description: "Te encontraron muteado en el Pair-Programming | Paga $4",
      tableMasterID: null
    },
    {
      id: 7,
      name: "Suerte",
      description: "Le hablaste a Anthony por un problema | Te salvás de migrar por errores administrativos",
      tableMasterID: null
    },
    {
      id: 8,
      name: "Suerte",
      description: "Te pasó la 4x4 de Diego | Retrocede 2 casilleros",
      tableMasterID: null
    },
    {
      id: 9,
      name: "Suerte",
      description: "Conseguiste el buda de la suerte en el repo | avanza 5 casilleros",
      tableMasterID: null
    },
    {
      id: 10,
      name: "Suerte",
      description: "Aprobaste el Proyecto Final | Avanza hasta la salida",
      tableMasterID: null
    },
    {
      id: 11,
      name: "Suerte",
      description: "Te copiaste en los checkpoints | Te vas directo a la migración",
      tableMasterID: null
    },
    {
      id: 12,
      name: "Suerte",
      description: "No te conectaste a las clases ni al stand-up | Pagas 5$ ",
      tableMasterID: null
    }
  ],
  comunal: [
    {
      id: 1,
      name: "Comunal",
      description: "Abandonás Henry en el M4 | Pagás $20",
      tableMasterID: null
    },
    {
      id: 2,
      name: "Comunal",
      description: "Entraste al Staff de Henry | Cobrás $10",
      tableMasterID: null
    },
    {
      id: 3,
      name: "Comunal",
      description: "Conseguiste un puesto de Semi-Senior directamente| Cobrás $10",
      tableMasterID: null
    },
    {
      id: 4,
      name: "Comunal",
      description: "Conseguiste trabajo en el extranjero | Cobrás $10",
      tableMasterID: null
    },
    {
      id: 5,
      name: "Comunal",
      description: "Repasaste con los videos de Franco | Te salvás de migrar por esforzarte",
      tableMasterID: null
    },
    {
      id: 6,
      name: "Comunal",
      description: "Ayudaste a Franco con la pregunta y te ganaste un Henry Coin | Cobras $11",
      tableMasterID: null
    },
    {
      id: 7,
      name: "Comunal",
      description: "Le preguntaste en el Q/A a Martu de la recursión | Te salvás de migrar por preguntar",
      tableMasterID: null
    },
    {
      id: 8,
      name: "Comunal",
      description: "Repasaste todos los días | Avanzaste 5 casilleros",
      tableMasterID: null
    }
  ]
}