const cardpropertiesData = [
    {
        name: " CSS",
        versionAlpha: 2,
        versionOne: 10,
        versionTwo: 30,
        versionThree: 90,
        versionFour: 160,
        versionPremium: 250,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 30,
        color: "brown"
    },
    {
        name: "HTML",
        versionAlpha: 4,
        versionOne: 20,
        versionTwo: 60,
        versionThree: 80,
        versionFour: 320,
        versionPremium: 450,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 30,
        color: "brown"
    },
    {
        name: "Postgres",
        versionAlpha: 6,
        versionOne: 30,
        versionTwo: 90,
        versionThree: 270,
        versionFour: 400,
        versionPremium: 550,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 50,
        color: "light blue"
    },
    {
        name: "SQLITE",
        versionAlpha: 6,
        versionOne: 30,
        versionTwo: 90,
        versionThree: 270,
        versionFour: 400,
        versionPremium: 550,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 50,
        color: "light blue"
    },
    {
        name: "MySQL",
        versionAlpha: 8,
        versionOne: 40,
        versionTwo: 100,
        versionThree: 300,
        versionFour: 450,
        versionPremium: 600,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 60,
        color: "light blue"
    },
    {
        name: "C#",
        versionAlpha: 10,
        versionOne: 50,
        versionTwo: 150,
        versionThree: 450,
        versionFour: 625,
        versionPremium: 750,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 70,
        color: "pink"
    },
    {
        name: "C++",
        versionAlpha: 10,
        versionOne: 50,
        versionTwo: 150,
        versionThree: 450,
        versionFour: 625,
        versionPremium: 750,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 70,
        color: "pink"
    },
    {
        name: "C",
        versionAlpha: 12,
        versionOne: 60,
        versionTwo: 180,
        versionThree: 500,
        versionFour: 700,
        versionPremium: 900,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 80,
        color: "pink"
    },
    {
        name: "BootStrap",
        versionAlpha: 14,
        versionOne: 70,
        versionTwo: 200,
        versionThree: 550,
        versionFour: 750,
        versionPremium: 950,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 90,
        color: "orange"
    },
    {
        name: "Diseño UI/UX",
        versionAlpha: 14,
        versionOne: 70,
        versionTwo: 200,
        versionThree: 550,
        versionFour: 750,
        versionPremium: 950,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 90,
        color: "orange"
    },
    {
        name: "Express",
        versionAlpha: 16,
        versionOne: 80,
        versionTwo: 220,
        versionThree: 600,
        versionFour: 800,
        versionPremium: 1000,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 100,
        color: "orange"
    },
    {
        name: "Vue",
        versionAlpha: 18,
        versionOne: 90,
        versionTwo: 250,
        versionThree: 700,
        versionFour: 875,
        versionPremium: 1050,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 110,
        color: "red"
    },
    {
        name: "Angular",
        versionAlpha: 18,
        versionOne: 90,
        versionTwo: 250,
        versionThree: 700,
        versionFour: 875,
        versionPremium: 1050,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 110,
        color: "red"
    },
    {
        name: "Node",
        versionAlpha: 20,
        versionOne: 100,
        versionTwo: 300,
        versionThree: 750,
        versionFour: 925,
        versionPremium: 1100,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 120,
        color: "red"
    },
    {
        name: "Python",

        versionAlpha: 22,
        versionOne: 110,
        versionTwo: 330,
        versionThree: 800,
        versionFour: 975,
        versionPremium: 1150,

        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 130,
        color: "yellow"
    },
    {
        name: "Java",
        versionAlpha: 22,
        versionOne: 110,
        versionTwo: 330,
        versionThree: 800,
        versionFour: 975,
        versionPremium: 1150,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 130,
        color: "yellow"
    },
    {
        name: "JavaScript",
        versionAlpha: 22,
        versionOne: 110,
        versionTwo: 330,
        versionThree: 800,
        versionFour: 975,
        versionPremium: 1150,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 130,
        color: "yellow"
    },
    {
        name: "Sequelize",
        versionAlpha: 26,
        versionOne: 130,
        versionTwo: 390,
        versionThree: 900,
        versionFour: 1100,
        versionPremium: 1275,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 150,
        color: "green"
    },
    {
        name: "GitHub",
        versionAlpha: 26,
        versionOne: 130,
        versionTwo: 390,
        versionThree: 900,
        versionFour: 1100,
        versionPremium: 1275,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 150,
        color: "green"
    },
    {
        name: "Git",
        versionAlpha: 28,
        versionOne: 150,
        versionTwo: 450,
        versionThree: 1000,
        versionFour: 1200,
        versionPremium: 1400,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 160,
        color: "green"
    },
    {
        name: "Redux",
        versionAlpha: 35,
        versionOne: 175,
        versionTwo: 500,
        versionThree: 1100,
        versionFour: 1300,
        versionPremium: 1500,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 175,
        color: "blue"
    },
    {
        name: "React",
        versionAlpha: 50,
        versionOne: 200,
        versionTwo: 600,
        versionThree: 1400,
        versionFour: 1700,
        versionPremium: 2000,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 200,
        color: "blue"
    }
]

module.exports = { cardpropertiesData }