
/**"property","service","lucky","comunal","railway","exit","jail","goJail","stop" */
const cardpropertiesData = [
    {
        id:0,
        type:"exit",
    },
    {
        id:1,
        type:"property",
        name: " CSS",
        versionAlpha: 2,
        versionOne: 10,
        versionTwo: 30,
        versionThree: 90,
        versionFour: 160,
        versionPremium: 250,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 30,
        color: "brown"
    },
    {
        id:2,
        type:"comunal",
    },
    {
        id:3,
        type:"property",
        name: "HTML",
        versionAlpha: 4,
        versionOne: 20,
        versionTwo: 60,
        versionThree: 80,
        versionFour: 320,
        versionPremium: 450,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 30,
        color: "brown"
    },
    {
        id:4,
        type:"tax",
    },
    {
        id:5,
        type:"railway",
        name: "HENRY M1",
        takeCheckpoint: 25,
        twoCheckpoint: 50,
        threeCheckpoint: 100,
        fourCheckpoint: 200
    },
    {
        id:6,
        type:"property",
        name: "Postgres",
        versionAlpha: 6,
        versionOne: 30,
        versionTwo: 90,
        versionThree: 270,
        versionFour: 400,
        versionPremium: 550,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 50,
        color: "light-blue"
    },
    {
        id:7,
        type:"lucky",
    },
    {
        id:8,
        type:"property",
        name: "SQLITE",
        versionAlpha: 6,
        versionOne: 30,
        versionTwo: 90,
        versionThree: 270,
        versionFour: 400,
        versionPremium: 550,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 50,
        color: "light-blue"
    },
    {
        id:9,
        type:"property",
        name: "MySQL",
        versionAlpha: 8,
        versionOne: 40,
        versionTwo: 100,
        versionThree: 300,
        versionFour: 450,
        versionPremium: 600,
        aditional: "además V4.0",
        commonVersion: 50,
        premiumVersion: 50,
        licenseValue: 60,
        color: "light-blue"
    },
    {
        id:10,
        type:"jail",
    },
    {
        id:11,
        type:"property",
        name: "C#",
        versionAlpha: 10,
        versionOne: 50,
        versionTwo: 150,
        versionThree: 450,
        versionFour: 625,
        versionPremium: 750,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 70,
        color: "pink"
    },
    {
        id:12,
        type:"service",
        name:"ELECTRICITY COMPANY",
        licenseValue:"75"
    },
    {
        id:13,
        type:"property",
        name: "C++",
        versionAlpha: 10,
        versionOne: 50,
        versionTwo: 150,
        versionThree: 450,
        versionFour: 625,
        versionPremium: 750,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 70,
        color: "pink"
    },
    {
        id:14,
        type:"property",
        name: "C",
        versionAlpha: 12,
        versionOne: 60,
        versionTwo: 180,
        versionThree: 500,
        versionFour: 700,
        versionPremium: 900,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 80,
        color: "pink"
    },
    {
        id:15,
        type:"railway",
        name: "HENRY M2",
        takeCheckpoint: 25,
        twoCheckpoint: 50,
        threeCheckpoint: 100,
        fourCheckpoint: 200
    },
    {
        id:16,
        type:"property",
        name: "BootStrap",
        versionAlpha: 14,
        versionOne: 70,
        versionTwo: 200,
        versionThree: 550,
        versionFour: 750,
        versionPremium: 950,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 90,
        color: "orange"
    },
    {
        id:17,
        type:"comunal",
    },
    {
        id:18,
        type:"property",
        name: "Diseño UI/UX",
        versionAlpha: 14,
        versionOne: 70,
        versionTwo: 200,
        versionThree: 550,
        versionFour: 750,
        versionPremium: 950,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 90,
        color: "orange"
    },
    {
        id:19,
        type:"property",
        name: "Express",
        versionAlpha: 16,
        versionOne: 80,
        versionTwo: 220,
        versionThree: 600,
        versionFour: 800,
        versionPremium: 1000,
        aditional: "además V4.0",
        commonVersion: 100,
        premiumVersion: 100,
        licenseValue: 100,
        color: "orange"
    },
    {
        id:20,
        type:"stop",
    },
    {
        id:21,
        type:"property",
        name: "Vue",
        versionAlpha: 18,
        versionOne: 90,
        versionTwo: 250,
        versionThree: 700,
        versionFour: 875,
        versionPremium: 1050,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 110,
        color: "red"
    },
    {
        id:22,
        type:"lucky",
    },
    {
        id:23,
        type:"property",
        name: "Angular",
        versionAlpha: 18,
        versionOne: 90,
        versionTwo: 250,
        versionThree: 700,
        versionFour: 875,
        versionPremium: 1050,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 110,
        color: "red"
    },
    {
        id:24,
        type:"property",
        name: "Node",
        versionAlpha: 20,
        versionOne: 100,
        versionTwo: 300,
        versionThree: 750,
        versionFour: 925,
        versionPremium: 1100,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 120,
        color: "red"
    },
    {
        id:25,
        type:"railway",
        name: "HENRY M3",
        takeCheckpoint: 25,
        twoCheckpoint: 50,
        threeCheckpoint: 100,
        fourCheckpoint: 200
    },
    {
        id:26,
        type:"property",
        name: "Python",
        versionAlpha: 22,
        versionOne: 110,
        versionTwo: 330,
        versionThree: 800,
        versionFour: 975,
        versionPremium: 1150,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 130,
        color: "yellow"
    },
    {
        id:27,
        type:"property",
        name: "Java",
        versionAlpha: 22,
        versionOne: 110,
        versionTwo: 330,
        versionThree: 800,
        versionFour: 975,
        versionPremium: 1150,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 130,
        color: "yellow"
    },
    {
        id:28,
        type:"service",
        name:"INTERNET COMPANY",
        licenseValue:"75",

    }, 
    {
        id:29,
        type:"property",
        name: "JavaScript",
        versionAlpha: 22,
        versionOne: 110,
        versionTwo: 330,
        versionThree: 800,
        versionFour: 975,
        versionPremium: 1150,
        aditional: "además V4.0",
        commonVersion: 150,
        premiumVersion: 150,
        licenseValue: 130,
        color: "yellow"
    },
    {
        id:30,
        type:"goJail",
    },
    {
        id:31,
        type:"property",
        name: "Sequelize",
        versionAlpha: 26,
        versionOne: 130,
        versionTwo: 390,
        versionThree: 900,
        versionFour: 1100,
        versionPremium: 1275,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 150,
        color: "green"
    },
    {
        id:32,
        type:"property",
        name: "GitHub",
        versionAlpha: 26,
        versionOne: 130,
        versionTwo: 390,
        versionThree: 900,
        versionFour: 1100,
        versionPremium: 1275,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 150,
        color: "green"
    },
    {
        id:33,
        type:"comunal",
    },
    {
        id:34,
        type:"property",
        name: "Git",
        versionAlpha: 28,
        versionOne: 150,
        versionTwo: 450,
        versionThree: 1000,
        versionFour: 1200,
        versionPremium: 1400,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 160,
        color: "green"
    },
    {
        id:35,
        type:"railway",
        name: "HENRY M4",
        takeCheckpoint: 25,
        twoCheckpoint: 50,
        threeCheckpoint: 100,
        fourCheckpoint: 200
    },
    {
        id:36,
        type:"lucky",
    },
    {
        id:37,
        type:"property",
        name: "Redux",
        versionAlpha: 35,
        versionOne: 175,
        versionTwo: 500,
        versionThree: 1100,
        versionFour: 1300,
        versionPremium: 1500,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 175,
        color: "blue"
    },
    {
        id:38,
        type:"taxVip",
    },
    {
        id:39,
        type:"property",
        name: "React",
        versionAlpha: 50,
        versionOne: 200,
        versionTwo: 600,
        versionThree: 1400,
        versionFour: 1700,
        versionPremium: 2000,
        aditional: "además V4.0",
        commonVersion: 200,
        premiumVersion: 200,
        licenseValue: 200,
        color: "blue"
    },
]

module.exports = { cardpropertiesData }