export { SET_TOKEN, SET_USER, SET_LOADING, SET_AUTH, SET_SOCKET } from "./auth";
export {
  GET_INFO,
  POST_PLAYERS,
  SET_STATUS_INFO,
  FILTER_LUCKY_RANDOM,
  FILTER_COMUNAL_RANDOM,
} from "./infoDb";
export {
  SET_STATUS_TABLE,
  SET_TABLE_GAME,
  SET_DATA_DEFAULT,
  SET_DATA_TARGET,
} from "./game";
export {
  SET_GAME,
  SET_TARGET_VALUE,
  SET_TURNS,
  KICK_PLAYER,
  SET_GAME_STATUS,
  SET_GAME_ROLL,
  BUY_PROPERTY_ACTION,
  SET_MOVE_TURN,
  SET_BALANCE,
  GO_TO_JAIL,
  SET_BUY_BOX,
  PLAYER_GAME_IS_OVER,
  TOKEN_PLAYERS
} from "./henropolyGame";
export { SET_VIEW } from "./view";
export { STATUS_TRADING } from "./henryTrading";
