export { SET_TOKEN, SET_USER, SET_LOADING, SET_AUTH, SET_SOCKET } from "./auth";
export {
  GET_INFO,
  POST_PLAYERS,
  SET_STATUS_INFO,
  FILTER_LUCKY_RANDOM,
  FILTER_COMUNAL_RANDOM,
} from "./infoDb";
export {
  SET_STATUS_TABLE,
  SET_TABLE_GAME,
  SET_DATA_DEFAULT,
  SET_DATA_TARGET,
} from "./game";
export {
  SET_GAME,
  SET_TARGET_VALUE,
  SET_TURNS,
  KICK_PLAYER,
  SET_GAME_STATUS,
  SET_GAME_ROLL,
  BUY_PROPERTY_ACTION,
  SET_MOVE_TURN,
  SET_BALANCE,
  GO_TO_JAIL,
  SET_BUY_BOX,
  GAME_ADIOS,
  SET_OWNER
} from "./henropolyGame";
export { SET_VIEW } from "./view";
export {
  STATUS_TRADING,
  SET_HOST_TRADER,
  SET_TRADING_FULL,
  SET_TRADE_OFERT_HOST,
  SET_TRADE_OFERT_OPONENT,
  SET_HOST_HENRY_COIN,
  SET_OPONENT_HENRY_COIN,
  SET_HOST_CONFIRMATION,
  SET_TARGET_CONFIRMATION
} from "./henryTrading";